/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgendaItem: typeof import('./src/components/AgendaItem.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    JumpToCurrentButton: typeof import('./src/components/JumpToCurrentButton.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    ProgressOverlay: typeof import('./src/components/ProgressOverlay.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    PwaPrompt: typeof import('./src/components/PwaPrompt.vue')['default']
    RoomItem: typeof import('./src/components/RoomItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeakerItem: typeof import('./src/components/SpeakerItem.vue')['default']
    SykomLogo: typeof import('./src/components/icons/SykomLogo.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TalkItem: typeof import('./src/components/TalkItem.vue')['default']
  }
}
